version: '3.9'
services:
    frontend:
        container_name: frontend
        build:
            context: ./se_academy_app_v2
            dockerfile: Dockerfile
        networks:
            - se_network
        ports:
            - "5173:80"
        depends_on:
            - backend
    backend:
        container_name: backend
        restart: always
        build:
            context: ./se_academy_api
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        networks:
            - se_network
        env_file:
            - ./se_academy_api/.env
        depends_on:
            - db
    db:
        image: postgres:16-alpine
        container_name: database
        restart: always 
        ports:
            - "54321:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        env_file:
            - ./se_academy_api/.env
        networks:
            - se_network

networks:
    se_network:
        driver: bridge

volumes:
    postgres_data: