services:
    frontend:
        container_name: frontend
        build:
            context: ./se_academy_app_v2
            dockerfile: Dockerfile
        networks:
            - se_network
        ports:
            - "5173:80"
        depends_on:
            - backend
    backend:
        container_name: backend
        restart: always
        build:
            context: ./se_academy_api
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        networks:
            - se_network
        env_file:
            - ./se_academy_api/.env
        depends_on:
            - db
    
    db:
        image: postgres:16-alpine
        container_name: database
        restart: always 
        ports:
            - "5432:5432"
        volumes:
            - se_academy_data:/var/lib/postgresql/data
        env_file:
            - ./se_academy_api/.env
        networks:
            - se_network
    se_adminer:
        image: adminer:latest
        container_name: adminerdb
        ports:
            - "8500:8080"
        networks:
            - se_network
        depends_on:
            - db

networks:
    se_network:
        driver: bridge

volumes:
    se_academy_data: